filter peers using non-std ports
ZcashFoundation/dnsseeder pull request #17
Opened 2022-06-02 21:01 UTC by conradoplg

We list all crawled IPs, but some of them use non-standard ports. But clients have no way to know what are the port of the peers, so we must only list ones using default ports.

I did the simplest thing that worked which is filtering at the last possible moment, when the seeder is queried. Since the current implementation is not particularly optimized (it iterates all the peers and shuffles them), this seems OK for now.

2022-06-06 00:23 UTC, teor2345 approved these changes
Looks good!

The port in the config is a string, which is more error-prone. But I don't want to change that existing code now. I'd rather we focus on replacing the seeder long-term.

2022-06-06 00:45 UTC, teor2345 requested changes
Can we also filter Flux/ZelCash peers as soon as we receive their addresses?

Flux didn't change their network magic, so our seeders will end up mapping their entire network as soon as a single Flux peer is in our peer set. (And they are already in Zcash node peer sets.)

But we can drop peer addresses on ports 16125 and 26125 as soon as they are received. That way, our seeders never make connections to them.

2022-06-06 23:56 UTC, conradoplg commented
> Can we also filter Flux/ZelCash peers as soon as we receive their addresses?
> 
> Flux didn't change their network magic, so our seeders will end up mapping their entire network as soon as a single Flux peer is in our peer set. (And they are already in Zcash node peer sets.)
> 
> But we can drop peer addresses on ports 16125 and 26125 as soon as they are received. That way, our seeders never make connections to them.

I ended up doing that in the next PR https://github.com/ZcashFoundation/dnsseeder/pull/18 for simplicity, let me know if that seems OK

2022-06-07 00:01 UTC, teor2345 approved these changes
Thanks, looks good!

2022-06-07 00:07 UTC, merged